import transamerica from "./Assets/transamerica.png";

export const products = [
  {
    id: 1,
    name: "Indexed Universal Life",
    type: "Insurance",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In convallis lectus vestibulum, accumsan purus nec, tempor sem. Cras vulputate massa vel porttitor tempus. Nulla facilisi. Nunc tristique id nisl sed scelerisque. Nunc vitae est convallis, pharetra risus accumsan, suscipit nibh. Ut vel diam rhoncus, hendrerit.",
    img: transamerica,
  },
  {
    id: 2,
    name: "name test2",
    type: "investment",
    info: "description test",
    img: transamerica,
  },
  {
    id: 3,
    name: "name test3",
    type: "annuity",
    info: "description test",
    img: transamerica,
  },
  {
    id: 4,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 5,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 6,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 7,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 8,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 9,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 10,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 11,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 12,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 13,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 14,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 15,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 16,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 17,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
  {
    id: 18,
    name: "name test",
    type: "insurance",
    info: "description test",
    img: transamerica,
  },
];
